version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./backend:/app
    working_dir: /app
    command: node index.js
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
      POSTGRES_DB: ipblogs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
